# Generated by Django 4.2.1 on 2023-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název auta', max_length=50, verbose_name='Název auta')),
                ('model_auta', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('off road', 'Off road'), ('kupé', 'Kupé'), ('kabriolet', 'Kabriolet'), ('dodávka', 'Dodávka')], default='Sedan', help_text='Vyberte model auta', max_length=100, verbose_name='Model auta')),
                ('cena', models.PositiveIntegerField(help_text='Zadejte cenu auta', verbose_name='Cena auta')),
                ('rok_vyroby', models.PositiveSmallIntegerField(help_text='Zadejte rok výroby auta', verbose_name='Rok výroby')),
                ('palivo', models.CharField(choices=[('benzín', 'Benzín'), ('nafta', 'Nafta'), ('elektro', 'Elektro'), ('hybrid', 'Hybrid')], help_text='Vyberte co používá auto za pohonou hmotu', max_length=100, verbose_name='Palivo')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Vyrobce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název výrobce aut', max_length=100, unique=True, verbose_name='Název výrobce')),
                ('datum', models.DateField(help_text='Zadejte datum založení firmy', verbose_name='Datum založení')),
                ('zeme', models.CharField(help_text='Zadejte zemi, ze které firma pochází', max_length=100, verbose_name='Země původu')),
            ],
            options={
                'verbose_name': 'Výrobce',
                'verbose_name_plural': 'Výrobci',
                'ordering': ['nazev'],
            },
        ),
    ]
