# Generated by Django 4.2.1 on 2023-05-09 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název autobazaru', max_length=100, verbose_name='Název autobazaru')),
                ('obec', models.CharField(help_text='Zadejte obec, ve které se autobazar nachází', max_length=100, verbose_name='Obec')),
                ('ulice', models.CharField(help_text='Zadejte ulici, ve které se autobazar nachází', max_length=50, verbose_name='Ulice')),
                ('psc', models.PositiveIntegerField(help_text='Zadejte PSČ', verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Autobazar',
                'verbose_name_plural': 'Autobazary',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadejte jméno zaměstnance', max_length=50, verbose_name='Jméno zaměstnance')),
                ('prijmeni', models.CharField(help_text='Zadejte příjmení zaměstnance', max_length=50, verbose_name='Příjmení zaměstnance')),
                ('obec', models.CharField(help_text='Zadejte obec, ve které zaměstnanec bydlí', max_length=100, verbose_name='Obec')),
                ('ulice', models.CharField(help_text='Zadejte ulici, ve které zaměstnanec bydlí', max_length=50, null=True, verbose_name='Ulice')),
                ('cislo_popisne', models.PositiveSmallIntegerField(help_text='Zadejte číslo popisné', verbose_name='Číslo popisné')),
                ('psc', models.PositiveIntegerField(help_text='Zadejte PSČ', verbose_name='PSČ')),
                ('telefon', models.CharField(help_text='Zadejte telefonní číslo zaměstnance (včetně předvolby)', max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte prosím platné telefonní číslo.', regex='^(\\+420)? ?[1-9][0-9]{2}( ?[0-9]{3}){2}$')], verbose_name='Telefon')),
                ('fotka', models.ImageField(blank=True, help_text='Nahrejte fotku zaměstnance', null=True, upload_to='zamestnanci', verbose_name='Fotka zaměstnance')),
            ],
            options={
                'verbose_name': 'Autobazar',
                'verbose_name_plural': 'Autobazary',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
    ]
