# Generated by Django 4.2.1 on 2023-05-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0002_autobazar_zamestnanec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamestnanec',
            options={'ordering': ['prijmeni', 'jmeno'], 'verbose_name': 'Zaměstnanec', 'verbose_name_plural': 'Zaměstnanci'},
        ),
    ]
