# Generated by Django 4.2.1 on 2023-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0003_alter_zamestnanec_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='autobazar',
            field=models.ManyToManyField(help_text='Vyberte autobazar, ve kterém se auto nachází', to='autobazar.autobazar', verbose_name='Autobazar'),
        ),
    ]
