# Generated by Django 4.2.1 on 2023-05-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0004_auto_autobazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='znacka',
            field=models.ForeignKey(default=0, help_text='Vyberte značku auta', on_delete=django.db.models.deletion.CASCADE, to='autobazar.vyrobce', verbose_name='Značka'),
        ),
    ]
