# Generated by Django 4.2.1 on 2023-05-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0005_auto_znacka'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamestnanec',
            name='autobazar',
            field=models.ForeignKey(default=0, help_text='Vyberte autobazar, ve kterém zaměstnanec pracuje', on_delete=django.db.models.deletion.CASCADE, to='autobazar.autobazar', verbose_name='Autobazar'),
        ),
    ]
