# Generated by Django 4.1.7 on 2023-06-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0007_auto_fotka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamestnanec',
            options={'ordering': ['prijmeni', 'jmeno'], 'verbose_name': 'Zamestnanec', 'verbose_name_plural': 'Zamestnanci'},
        ),
    ]
