# Generated by Django 4.1.7 on 2023-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobazar', '0009_autobazar_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobazar',
            name='fotka',
            field=models.ImageField(blank=True, default='uploads/default.jpg', help_text='Nahrejte logo autobazaru', null=True, upload_to='autobazary', verbose_name='Logo autobazaru'),
        ),
    ]
